# Generated by Django 6.0.2 on 2026-03-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_description_alter_product_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='asset_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
